name: 'Satis Package Repository Builder'
description: 'Build a custom php-packages repository using satis and satisfy'
runs:
  using: 'docker'
  image: 'ghcr.io/ingenerator/action-satis-builder:experiment'
  
